import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import HeaderTop from "@/components/Common/HeaderTop";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const anikBangla = localFont({
  src: "./fonts/AnekBangla-VariableFont_wdth,wght.ttf",
  weight: "100 900"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="light" lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.className} ${geistMono.className} ${anikBangla.className} antialiased`}
      >
        <HeaderTop></HeaderTop>
        {children}
      </body>
    </html>
  );
}
